### ISSUE TITLE
Error when running microcloud init

### ISSUE THREAD

**Issue by andybroger** [canonical/microcloud#109] opened 2023-05-14 11:31 UTC
After all questions of `microcloud init` are answered. And the cluster starts to initialize i get following error:

```
Initializing a new cluster
 Local MicroCloud is ready
 Local LXD is ready
 Local MicroCeph is ready
Error: Failed to bootstrap local MicroOVN: Failed to generate the daemon configuration: Remote couldn't be found for "metal1"
```

**Comment by tomponline** [comment] 2023-05-14 11:33
Duplicate of https://github.com/canonical/microcloud/issues/107#issuecomment-1543543977

**Closed by tomponline** 2023-05-14 11:33 UTC
